info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
grails:
    codegen:
        defaultPackage: com.arjang
    profile: web
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
                - text/html
                - application/xhtml+xml
            js: text/javascript
            json:
                - application/json
                - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
                - application/hal+json
                - application/hal+xml
            xml:
                - text/xml
                - application/xml
    views:
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlet: html
                taglib: none
                staticparts: none
        default:
            codec: html

hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    pooled: true
    jmxExport: true

environments:
    development:
        logging.level.com.arjang: INFO
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:mem:devoneDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
        dataSources:
            myotherdb:
                dbCreate: create-drop
                transactional: true
                readOnly: true
                url: jdbc:h2:mem:devtwoDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    test:
        logging.level.com.arjang: INFO
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:mem:devoneDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
        dataSources:
            myotherdb:
                dbCreate: create-drop
                transactional: true
                readOnly: true
                url: jdbc:h2:mem:devtwoDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE

